name: 'Backport Action'
description: 'Backport merged pull requests to other branches via labels'
inputs:
  github_token:
    description: The access token that will be used to create the backport pull requests and perform other operations
    required: true
  autoBackportLabelPrefix:
    description: Backport a pull request to specific branches based on the labels applied
    required: false
  repoForkOwner:
    description: The owner of the repo where the backport branch will be pushed to. Defaults to the current repo
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: git-branch
  color: green
